language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install flake8"
  - "pip install -r requirements.txt"
# command to run tests
script: flake8 --max-line-length=100 --max-complexity=24 --statistics --benchmark --ignore=E5,F4 ./
